# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Leonix Fraud Engine"
client_id = "ccedb919ae2e9f610583c98a7839e5c1"
application_url = "https://placeholder.example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-leonix.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,read_orders,write_fulfillments,read_customers,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://placeholder.example.com/auth/callback",
  "https://placeholder.example.com/auth/shopify/callback",
  "https://placeholder.example.com/exitiframe",
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["refunds/create"]
  uri = "/webhooks"

[pos]
embedded = false
