# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ccedb919ae2e9f610583c98a7839e5c1"
name = "Leonix Fraud Engine"
application_url = "https://shopify-app-khnbyrj5aa-uc.a.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "test-leonix.myshopify.com"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [
    "orders/create",
    "orders/updated",
    "refunds/create",
    "app/uninstalled",
    "customers/data_request",
    "customers/redact",
    "shop/redact",
  ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_themes,write_fulfillments,write_orders,write_themes"

[auth]
redirect_urls = [
  "https://shopify-app-khnbyrj5aa-uc.a.run.app/auth/callback",
  "https://shopify-app-khnbyrj5aa-uc.a.run.app/auth/shopify/callback",
  "https://shopify-app-khnbyrj5aa-uc.a.run.app/exitiframe"
]

[pos]
embedded = false
